version: "3"
services: 
  db:
    image: mysql:5.7
    command: mysqld --skip-ssl
    ports:
      - "32000:3306"
    env_file: ./deploy/local.env.conf
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app: 
    build: ./
    ports: 
      - 1337:80
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
    env_file: ./deploy/local.env.conf
    volumes: 
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - db